# Generated by Django 5.0.7 on 2024-07-24 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_likes_question_unlikes_delete_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(related_name='liked_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='unlikes',
            field=models.ManyToManyField(related_name='unliked_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
