# Generated by Django 5.0.7 on 2024-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_comment_likes_comment_unlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
